name: macos-x86_64-ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run distcheck
      run: cd mk && make -f mu0.mk distcheck

# EOF