name: Windows CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    shell: bash

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name:
      run: echo "PATH=$PATH:C:\msys64\mingw64\bin" >> $GITHUB_ENV
    - name: Run distcheck
      run: cd mk && make -f mu0.mk distcheck

# EOF